ar -M<<"EOF"
CREATE Build/Debug-linux-x86_64/Ange/libAngePacked.a
ADDLIB Build/Debug-linux-x86_64/Ange/libAnge.a
ADDLIB ../Vendor/GLFW/Build/Debug-linux-x86_64/GLFW/libGLFW.a
ADDLIB ../Vendor/glad/Build/Debug-linux-x86_64/glad/libglad.a
ADDLIB ../Vendor/freetype/Build/Debug-linux-x86_64/FreeType/libFreeType.a
ADDLIB ../Vendor/libpng/Build/Debug-linux-x86_64/libpng/liblibpng.a
ADDLIB ../Vendor/libjpeg/Build/Debug-linux-x86_64/libjpeg/liblibjpeg.a
ADDLIB ../Vendor/zlib/Build/Debug-linux-x86_64/zlib/libzlib.a
SAVE
END
EOF
